### ISSUE TITLE
WHen trying to add new bookmark , getting error - Error: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by maheshuma926** [UrosVuj/Explorer-Bookmark#11]
Getting below error:
Error: The "path" argument must be of type string. Received type undefined

Plugin Version: v0.0.5
VS Code Version details:  
Version: 1.79.0 (Universal)
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:29:00.206Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.4.0

**Comment by MagoMaverick** [comment]
Same here, probably with some VSCODE update, it stopped works.

**Comment by jiyeong-kwon** [comment]
Same here.

**Comment by rfirefly** [comment]
```javascript
vscode.workspace.fs // this api has a breake change
``` 
i have been forked it.

**Comment by georgiIvanov** [comment]
I'm experiencing the same issue.
Plugin v0.0.5
VSCode: Version: 1.85.1 (Universal) Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
macOS: 14.2 (23C64)

**Comment by UrosVuj** [comment]
Hi folks, I've published version 1.0.1 with the fix for this issue :)
