### ISSUE TITLE
Files won't open after restart VS Code. 

### ISSUE THREAD

**Issue by LostGuard** [UrosVuj/Explorer-Bookmark#2]
Added individual files do not open after restarting visual studio. If you add a folder, then the files from it open normally. 

![изображение](https://user-images.githubusercontent.com/1542114/149601163-de242e3c-fdd8-456e-a187-b9a3008c728d.png)

OS - Windows 7

**Comment by UrosVuj** [comment]
Hm, this used to work back when the extension launched. It seems that when passing the restored URIs from the previous session, the `vscode.open` command didn't recognize the URIs as valid for some reason and threw an error. When reconstructing the URIs by using `vscode.Uri.parse(oldUri.path)` everything works.

Anyhow, all fixed now.

**Comment by LostGuard** [comment]
works well, thanks.
